version: '3.8'

services:
  web:
    build:
      context: ..                   # Đi lùi ra thư mục gốc (fastapi_starter) để làm gốc build
      dockerfile: docker/Dockerfile  # Chỉ đường dẫn cụ thể tới file Dockerfile này
    container_name: fastapi_web_app
    ports:
      - "8000:8000"
    volumes:
      - ..:/app                     # Đồng bộ toàn bộ thư mục gốc vào /app trong container để hot-reload
    environment:
      - ENV=development